---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 --exclude=.venv/
platforms:
  - name: Bionic
    image: ubuntu:18.04
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
