## Travis CI configuration for the ansible-role project template.
##
##  <https://travis-ci.org/mdklatt/cookiecutter-ansible-role>
##
language: python

python:
  - "2.7"

branches:
  only:
    - master
    - dev

sudo: false  # use container infrastructure

install:
  - pip install ansible
  - pip install -r requirements.txt -r tests/requirements.txt

script:
  - python tests/test_template.py
