# <https://travis-ci.org/mdklatt/cookiecutter-ansible-role>
language: python

python:
  - "3.7"

services:
  - docker

branches:
  only:
    - main
    - dev

sudo: false  # use container infrastructure


install:
  - python -m pip install -r requirements.txt

script:
  - python tests/test_template.py
